### ISSUE TITLE
Include realm in the taxdump

### ISSUE THREAD

**Issue by apcamargo** [shenwei356/ictv-taxdump#1]
The highest rank in the ICTV taxonomy is the "realm", which is now being ignored in the `ictv-taxdump`. Because the `taxonkit create-taxdump` command only supports a fixed number of ranks, there's no way to include it without removing other ranks. Because having the realm is (to my purposes) usually more important than the virus name (which is being treated as subspecies), I'm building a taxdump with "shifted" ranks:

```bash
# download the latest VMR from ICTV
aria2c -x 4 -o ictv.xlsx "https://talk.ictvonline.org/taxonomy/vmr/m/vmr-file-repository/13426/download"

# convert xlsx to tsv
csvtk xlsx2csv ictv.xlsx \
    | csvtk csv2tab \
    | sed 's/\xc2\xa0/ /g' \
    | csvtk replace -t -F -f "*" -p "^\s+|\s+$" \
    > ictv.tsv

# choose columns, and remove duplicates
csvtk cut -t -f "Realm,Subrealm,Kingdom,Subkingdom,Phylum,Subphylum,Class,Subclass,Order,Suborder,Family,Subfamily,Genus,Subgenus,Species" ictv.tsv \
    | csvtk uniq -t -f "Realm,Subrealm,Kingdom,Subkingdom,Phylum,Subphylum,Class,Subclass,Order,Suborder,Family,Subfamily,Genus,Subgenus,Species" \
    | csvtk del-header -t \
    > ictv.taxonomy.tsv

taxonkit create-taxdump -K 1 -P 3 -C 5 -O 7 -F 9 -G 11 -S 13 -T 15 \
    --rank-names "realm","kingdom","phylum","class","order","family","genus","species" \
    ictv.taxonomy.tsv --out-dir ictv-taxdump
```

As of note, I'm using the new 2022 VMR release, which is different from the one used in this repository.

This is just a suggestion though. I got the feeling that including the realm is probably more important than the virus name for most applications. On top of that, ["species" is the lowest rank in the ICTV taxonomy.](https://talk.ictvonline.org/information/w/ictv-information/383/ictv-code). The virus name column, as far as I know, is only used because some species will have multiple representative genomes (but only one will be the "exemplar").

Ideally, we would have a taxdump that includes all the ICTV ranks (including subgenus, subfamily, suborder, etc.), but this might conflict with taxonkit's philosophy of using NCBI's "canonical ranks".

**Comment by shenwei356** [comment]
I just miss the MSL37 release.

> The virus name column, as far as I know, is only used because some species will have multiple representative genomes (but only one will be the "exemplar").

Subspecies rank is actually optional. "Exemplar or additional isolate" can also be treated as subspecies, but the value "E" or "A" is less informative so I ignore this.

> Ideally, we would have a taxdump that includes all the ICTV ranks (including subgenus, subfamily, suborder, etc.), but this might conflict with taxonkit's philosophy of using NCBI's "canonical ranks".

move this to https://github.com/shenwei356/taxonkit/issues/60.

**Comment by shenwei356** [comment]
Implemented, please test:

[ictv-taxdump.tar.gz](https://github.com/shenwei356/ictv-taxdump/files/8798951/ictv-taxdump.tar.gz)

The readme is updated. [2fbf736](https://github.com/shenwei356/ictv-taxdump/commit/2fbf73637fb740126b5ccf23f281cbaca684b012)

```
 $ taxonkit list --ids 1 \
     | taxonkit lineage -L -r \
     | csvtk freq -H -t -f 2 -n \
     | csvtk pretty -H -t            
 no rank         1
 Subphylum       2
 Realm           6
 Suborder        8
 Kingdom         10
 Phylum          17
 Class           39
 Order           65
 Subgenus        84
 Subfamily       168
 Family          233
 Genus           2606
 Species         10434
 Virus name(s)   10539
```

also see the changes of `taxonkit create-taxdump`: https://github.com/shenwei356/taxonkit/issues/60

**Comment by apcamargo** [comment]
Awesome! Thanks!

**Comment by shenwei356** [comment]
Updated again, removing duplicated taxids in taxid.map.

Also release two versions, `ictv-taxdump.tar.gz` is a subset of `ictv-taxdump-with-subpsecies.tar.gz`.

**Comment by shenwei356** [comment]
Check the new version:

https://github.com/shenwei356/ictv-taxdump/releases/tag/v37.0

created by https://github.com/shenwei356/taxonkit/releases/tag/v0.12.0-alpha

**Comment by lonestarling** [comment]
Hi guys
Thank you for your awesome script，i try it  so many times to create the ictv-taxdump ，but i fail in the step of “taxonkit create-taxdump” and meet the error about 
“ [ERRO] taxonomy data not found, please download and uncompress ftp://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz, and copy "names.dmp", "nodes.dmp", "delnodes.dmp", and "merged.dmp" ”
can you give some advice about this.

Appreciate it
L

**Comment by shenwei356** [comment]
Oh I see, taxonkit check the default taxdump files every time. just do what it said.

> please download and uncompress   ftp://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz, and copy "names.dmp", "nodes.dmp", "delnodes.dmp", and "merged.dmp to ~/.taxonkit/

**Comment by shenwei356** [comment]
@lonestarling  It skips checking the data directory for `create-taxdump` and `taxid-changelog` now.

- [taxonkit_windows_amd64.exe.tar.gz](https://github.com/shenwei356/ictv-taxdump/files/8875008/taxonkit_windows_amd64.exe.tar.gz)
- [taxonkit_linux_amd64.tar.gz](https://github.com/shenwei356/ictv-taxdump/files/8875006/taxonkit_linux_amd64.tar.gz)
- [taxonkit_darwin_amd64.tar.gz](https://github.com/shenwei356/ictv-taxdump/files/8875004/taxonkit_darwin_amd64.tar.gz)

Please open another issue for a different topic next time, thanks.

**Comment by lonestarling** [comment]
> Oh I see, taxonkit check the default taxdump files every time. just do what it said.
> 
> > please download and uncompress   ftp://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz, and copy "names.dmp", "nodes.dmp", "delnodes.dmp", and "merged.dmp to ~/.taxonkit/

Thank you so much, sir,  i will try it again.
